site_name: John Sipahioglu
nav: 
  - Home: index.md
  - CSE122:
    - Home: CSE122/index.md
    - Setup Help: CSE122/setup.md
    - Creating Labs: CSE122/dotnet_commands.md
    - Terminal Basics: CSE122/terminal_basics.md
  - NET264:
    - Week 1: NET264/week1.md
    - Weeks 2 and 3: NET264/week2.md
theme: 
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true 
